# Generated by Django 4.2.7 on 2023-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
