# Generated by Django 4.2.7 on 2023-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_faculty_password_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
